"""add_price_change_audit

Revision ID: 395e1c1eb9d0
Revises: e559e6c16697
Create Date: 2025-12-29 17:16:55.773545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '395e1c1eb9d0'
down_revision: Union[str, Sequence[str], None] = 'e559e6c16697'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('material_groups_name_key'), 'material_groups', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('material_groups_name_key'), 'material_groups', ['name'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
