"""add_material_groups

Revision ID: e559e6c16697
Revises: dec47bb3f2e8
Create Date: 2025-12-29 12:57:22.876640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e559e6c16697'
down_revision: Union[str, Sequence[str], None] = 'dec47bb3f2e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Utwórz tabelę material_groups używając raw SQL (enum już istnieje)
    op.execute("""
        CREATE TABLE material_groups (
            id SERIAL PRIMARY KEY,
            name VARCHAR(100) NOT NULL UNIQUE,
            category materialcategory NOT NULL,
            description TEXT,
            display_order INTEGER NOT NULL DEFAULT 0,
            is_active BOOLEAN NOT NULL DEFAULT true
        )
    """)
    op.create_index(op.f('ix_material_groups_name'), 'material_groups', ['name'], unique=True)

    # Dodaj kolumny do materials
    op.add_column('materials', sa.Column('group_id', sa.Integer(), nullable=True))
    op.add_column('materials', sa.Column('composition', sa.String(length=300), nullable=True))
    op.add_column('materials', sa.Column('tensile_strength', sa.String(length=50), nullable=True))
    op.add_column('materials', sa.Column('yield_strength', sa.String(length=50), nullable=True))
    op.add_column('materials', sa.Column('applications', sa.Text(), nullable=True))
    op.add_column('materials', sa.Column('display_order', sa.Integer(), nullable=False, server_default='0'))
    op.alter_column('materials', 'standard',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('materials', 'description',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=True)
    op.create_index(op.f('ix_materials_group_id'), 'materials', ['group_id'], unique=False)
    op.create_foreign_key(None, 'materials', 'material_groups', ['group_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('materials_group_id_fkey', 'materials', type_='foreignkey')
    op.drop_index(op.f('ix_materials_group_id'), table_name='materials')
    op.alter_column('materials', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.alter_column('materials', 'standard',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.drop_column('materials', 'display_order')
    op.drop_column('materials', 'applications')
    op.drop_column('materials', 'yield_strength')
    op.drop_column('materials', 'tensile_strength')
    op.drop_column('materials', 'composition')
    op.drop_column('materials', 'group_id')

    # Drop material_groups table
    op.drop_index(op.f('ix_material_groups_name'), table_name='material_groups')
    op.drop_table('material_groups')
    # ### end Alembic commands ###
